feat: added github icon to the footer
distributeaid/distributeaid.org pull request #551
Opened 2022-08-26 00:55 UTC by rcmtcristian

have to fix flex alignment, and change the color of the icon

2022-08-30 22:29 UTC, coderbyheart requested changes
Please use SVG for the logo.

2022-08-30 23:49 UTC, rcmtcristian commented
changed the color of the github icon and margin for the footer

2022-08-31 00:14 UTC, rcmtcristian commented
Missed that request and closed it but now it should be updated.

2022-08-31 06:56 UTC, coderbyheart requested changes
Please use a proper SVG, not a traced bitmap.

2022-08-31 09:57 UTC, coderbyheart commented
> Please use a proper SVG, not a traced bitmap.

GitHub Logos can be found on https://github.com/logos

2022-08-31 11:28 UTC, jtfairbank commented
Hey @coderbyheart I was looking at those with @rcmtcristian when we did our onboarding session.  We went with the .png for starters to focus on the code.

@rcmtcristian could you see if you could covert the `.eps` or `.ai` vector images available on the github logo download page to a `.svg`?  That seems like it'd resolve this issue!

2022-08-31 14:53 UTC, rcmtcristian commented
> Hey @coderbyheart I was looking at those with @rcmtcristian when we did our onboarding session. We went with the .png for starters to focus on the code.
> 
> @rcmtcristian could you see if you could covert the `.eps` or `.ai` vector images available on the github logo download page to a `.svg`? That seems like it'd resolve this issue!

just converted them in like that, hopefully it was the correct way

2022-08-31 14:59 UTC, coderbyheart commented on src/components/social-media/SocialMediaLink.tsx
> +      <aside className="w-16 h-16 flex flex-col justify-center items-center -mr-4 ">
```suggestion
      <aside className="w-16 h-16 flex flex-col justify-center items-center -mr-4">
```

2022-08-31 15:16 UTC, coderbyheart requested changes
Icon should be blue.

![image](https://user-images.githubusercontent.com/188915/187714988-bb3c9537-0da0-4d51-85fd-860836ec7ddf.png)

2022-08-31 15:25 UTC, jtfairbank commented
@rcmtcristian you should be able to open the `.svg` file in a text editor and set the color to Distribute Aid's blue hex code `#09328B`.  You can look at the other social icon `.svg` files for how to do this using the `fill` attribute (`fill="#09328B"`).

2022-08-31 15:33 UTC, rcmtcristian commented
super weird I made sure it had the correct color, and it showed it correct on my end. gonna recheck it

2022-08-31 15:37 UTC, rcmtcristian commented
just saw that my end had not updated correctly after I changed the file, fixed now to how it should be. thank you for being so patient

2022-08-31 15:44 UTC, jtfairbank commented
Hey @rcmtcristian no worries at all!  It's often easier to see these things as reviewers.  Last request: looks like there are some little black dots in the tail, can you try finding out where the color is set for those in the `.svg` and updating it to the DA blue as well?  Thanks!

2022-08-31 15:51 UTC, rcmtcristian commented
dots in the svg changed to the correct color

2022-08-31 15:53 UTC, jtfairbank commented
Thanks so much @rcmtcristian! :100: 

Merge when ready @coderbyheart, or def point out any other change requests! :smile:

2022-08-31 19:43 UTC, hola-soy-milk approved these changes
Just gave this a look, fantastic work @rcmtcristian!

2022-08-31 19:48 UTC, coderbyheart commented
LGTM, however, did you notice that the new icon is included using an `<img>` tag, while the others are data embed?

2022-08-31 19:50 UTC, hola-soy-milk commented
> LGTM, however, did you notice that the new icon is included using an `<img>` tag, while the others are data embed?

Aha! Could that be related to the source? Given it's a Github SVG?

2022-08-31 19:56 UTC, coderbyheart commented
Ah, I see. The SVG includes multiple logos, however the SVG viewbox crops it.
Will fix it.

2022-08-31 20:01 UTC, merged

2022-08-31 20:02 UTC, hola-soy-milk commented
Yay! Thank you all so much! 🎉

2022-08-31 20:04 UTC, rcmtcristian commented
Awesome! thank you all so much for guiding me through

2022-08-31 20:12 UTC, coderbyheart commented
![Teamwork!](https://media.giphy.com/media/VgeGEVTdwzZao/giphy.gif)