Fixing issue: Mobile view has padding on the right #563
distributeaid/distributeaid.org pull request #579
Opened 2022-09-02 07:08 UTC by Pathholder1806

Hey @jtfairbank !

So as you suggested that the dimensions of the **react-globe** should be dynamic.

So I came up with a solution as described below:
1. I have taken the **dimensions of the globe** as a react state because we need the re-renders whenever the screen size changes so that **the globe object is re-rendered with the new appropriate width**.
2. I have used the an 'event listener' on the window object which is listening to the 'resize' and as a callback for it I have passed a function which updates the **globe dimension state** which apparently passes new width to the globe component and causes it to re-render with new width.

So now whenever the width of the parent container of **react-globe** changes, the width of **react-globe** also changes and the state updating causes its re-render.
Whenever the width of parent is more than 384(default), the width of **react-globe** is set to 384 and when the parent shrinks below 384px, the **react-globe** width is set to the full-width of the parent.

I am creating the pull request kindly review my changes and suggest any improvements you feel!

2022-09-02 07:26 UTC, Pathholder1806 commented
Hey @jtfairbank !

The is the selector in the index.css, **.link** that is causing errors in my local system

![image](https://user-images.githubusercontent.com/61896647/188082081-28c3bdcf-6fa7-4a72-b728-19dfe140271b.png)

Now I don't know if is this is a problem with my local setup only or is it a actual error of the code.

2022-09-02 07:43 UTC, coderbyheart commented
Preview: https://deploy-preview-579--da-landing-2.netlify.app/

2022-09-02 07:45 UTC, coderbyheart requested changes

2022-09-02 07:45 UTC, coderbyheart commented on src/components/vis/shipments-on-globe.tsx
> +  // console.log('arcsData', arcsData)
```suggestion
```

2022-09-02 07:45 UTC, coderbyheart commented on src/components/vis/shipments-on-globe.tsx
> +  let resizeGlobeSize = () => {
```suggestion
  const resizeGlobeSize = () => {
```

2022-09-02 07:45 UTC, coderbyheart commented on src/components/vis/shipments-on-globe.tsx
> +    let globeSectionWidth =
```suggestion
    const globeSectionWidth =
```

2022-09-02 07:45 UTC, coderbyheart commented on src/stylesheets/index.css
> +} */
```suggestion
.link {
  @apply text-navy-700 hover: underline font-semibold;
}
```

Unrelated change, please address in separate issue.

2022-09-02 07:46 UTC, coderbyheart reviewed
Otherwise good solution!

2022-09-02 07:48 UTC, Pathholder1806 commented
Thanks @jtfairbank !
Can we proceed with merging then ?

2022-09-02 07:53 UTC, coderbyheart commented on src/stylesheets/index.css
> +  @apply text-navy-700 hover: underline font-semibold;
```suggestion
  @apply text-navy-700 hover:underline font-semibold;
```

2022-09-02 07:54 UTC, merged

2022-09-05 12:08 UTC, jtfairbank commented
Resolves #563 (just adding this to link to the issue).