Calculating totals shipments extracted to helper class Closes #66
distributeaid/distributeaid.org pull request #67
Opened 2021-10-21 18:31 UTC by dolatapatryk

Refactor for #66

Calculating totals shipments extracted to helper class.

2021-10-21 18:32 UTC, ghost commented
### Changes to your CodeSee Architecture Map:
[![View a CodeSee Map of these changes](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/distributeaid/distributeaid.org/67/129c33d2/b8fd6aaa993f6c4404375545769b6e6914c4aa2b.svg)](https://app.codesee.io/r/prs?id=6521&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

View [this PR diagram as an interactive map](https://app.codesee.io/r/prs?id=6521&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

View [more CodeSee Maps](https://app.codesee.io/r/maps?src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2021-10-25 18:11 UTC, hola-soy-milk requested changes
Thank you so much for your contribution! I left one minor comment in, could you please take a look?

2021-10-25 18:11 UTC, hola-soy-milk commented on .gitignore
> +.idea/
Is this needed? I think it might be an IDE feature. 

If not, can we remove it?

2021-10-25 19:52 UTC, dolatapatryk commented on .gitignore
> +.idea/
Yep, my IDE generates such directory so I wanted to exclude it, maybe for further purpose too. But I think I can remove this. I will handle it in a minute.

2021-10-26 09:12 UTC, dolatapatryk commented
@ramonh Done :)

2021-10-27 14:18 UTC, dolatapatryk commented
@ramonh sorry for asking but is my solution good? I'm asking because October is ending and I'm trying to get my hacktober points :)

2021-10-27 17:21 UTC, hola-soy-milk commented
Eek! Sorry @dolatapatryk, Dunno why I missed it yesterday. Will take a look right away!

2021-10-27 17:21 UTC, hola-soy-milk approved these changes
Looks brilliant, thank you so much!

2021-10-27 17:22 UTC, merged

2021-10-27 18:01 UTC, dolatapatryk commented
@ramonh thank you cery much! 😎