Storybook WIP
distributeaid/distributeaid.org pull request #773
Opened 2022-10-17 15:33 UTC by fredericbonnet

2022-10-17 15:33 UTC, ghost commented
<details>
<summary><b>👇 <a href="https://app.codesee.io/r/reviews?pr=773&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org">Click on the image</a> for a new way to code review</b>
</summary>

  - Make big changes easier — review code in small groups of related files
  - Know where to start — see the whole change at a glance
  - Take a code tour — explore the change with an interactive tour
  - Make comments and review — all fully sync’ed with github

    [Try it now!](https://app.codesee.io/r/reviews?pr=773&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)
</details>

[![Review these changes using an interactive CodeSee Map](https://s3.us-east-2.amazonaws.com/maps.codesee.io/images/github/distributeaid/distributeaid.org/773/d27d908c/ab7c381c37248d25d8ea834d8b756cc5ef21da50.svg)](https://app.codesee.io/r/reviews?pr=773&src=https%3A%2F%2Fgithub.com%2Fdistributeaid%2Fdistributeaid.org)

#### Legend
![CodeSee Map Legend](https://app.codesee.io/Legend_v2.png)

2022-10-17 18:31 UTC, jtfairbank requested changes
*(using [conventional comments](https://conventionalcomments.org/) style feedback)*

- praise: Storybook looks awesome!  I think this will help a ton when collaborating with content contributors on early component iterations, as well as allowing other devs to reuse / remix each other's work more easily.

- suggestion (blocking): Add some brief documentation about Storybook in the `/README.md` file, including a brief overview, a link to their docs, and the command to run the storybook server.

- suggestion (non-blocking): Include instructions in the `/.gitpod.yml` file to automatically run the storybook server on a bash shell so that it's available out of the box for contributors using gitpod.  Alternatively, make an issue that someone else could pick up?

- question: Would it make sense to get a bunch of small issues up asking contributors to add Storybook descriptions for different components?

- question: Is there a way to use storybook to test component rendering / behaviour?  Like, use Storybook scenarios with Playwright to to enable end-to-end testing before the component is ready for production?

2022-10-17 18:34 UTC, jtfairbank commented
Hey @fredericbonnet storybook looks great, let's get it in there!  Have a bit of feedback for you above, want to take another pass and then mark this PR as "ready for review" so we can get it merged in?  Thanks so much for taking the initiative here.

2022-10-22 20:16 UTC, fredericbonnet commented
Hey, sorry for the late reply I was on business travel. Here are some answers to your feedback above:

> * praise: Storybook looks awesome!  I think this will help a ton when collaborating with content contributors on early component iterations, as well as allowing other devs to reuse / remix each other's work more easily.

👍

> * suggestion (blocking): Add some brief documentation about Storybook in the `/README.md` file, including a brief overview, a link to their docs, and the command to run the storybook server.

Sure, will do.

> * suggestion (non-blocking): Include instructions in the `/.gitpod.yml` file to automatically run the storybook server on a bash shell so that it's available out of the box for contributors using gitpod.  Alternatively, make an issue that someone else could pick up?

I tried adding `yarn storybook` to this file on my GitPod instance but for some reason it insists on starting immediately instead of waiting for the build to complete, l'll push my change there and hopefully we'll solve this during review.

> * question: Would it make sense to get a bunch of small issues up asking contributors to add Storybook descriptions for different components?

Definitely! I think I've solved the main roadblock so that we can add stories easily for all types of components including those that depend on static queries (e.g. `MissionSection`), just by copy/pasting the existing ones. And I know many sites also use Storybook not only for components but for full page development as well, (e.g. [The Guardian](https://main--5dfcbf3012392c0020e7140b.chromatic.com/?path=/story/layouts-palettes--event-palette)).

> * question: Is there a way to use storybook to test component rendering / behaviour?  Like, use Storybook scenarios with Playwright to to enable end-to-end testing before the component is ready for production?

This is an area I don't know very well, but I know there are some [test-related addons](https://storybook.js.org/addons/tag/test/) that you can integrate with your CI, for example:

- [Storybook Test Runner](https://storybook.js.org/addons/@storybook/test-runner): I think this one is what you're looking for, it mounts your stories and runs them with Jest and Playwright, and you can provide a "[play function](https://storybook.js.org/docs/react/writing-stories/play-function)" with your assertions.
- [Storybook addon Jest](https://storybook.js.org/addons/@storybook/addon-jest) integrates your Jest test results within the Storybook ui

You can also do [visual regression testing](https://storybook.js.org/docs/react/writing-tests/visual-testing) and [accessibility compliance testing](https://storybook.js.org/addons/@storybook/addon-a11y).

2022-10-23 16:37 UTC, fredericbonnet commented
The PR is now ready for review. Since the first draft I've added stories for several other components and pages.

I've also installed the [Accessibility addon](https://storybook.js.org/addons/@storybook/addon-a11y), which gives interesting results on some components (most notably Footer component and Simple layout), just click on the **Accessibility** tab in the bottom panel for the results. The addon also provides a very convenient vision simulator if you want to check for the most common vision deficiencies:

![addon-a11y](https://user-images.githubusercontent.com/11368533/197404283-8ad919ac-ba83-443f-b65a-2f738b426a59.png)

2022-10-23 18:03 UTC, jtfairbank approved these changes
Looks great!

2022-10-23 18:03 UTC, merged